MODEL:
  TYPE: vssm
  NAME: vssm1_base_0229
  DROP_PATH_RATE: 0.6
  NUM_CLASSES: 5
  CLASS_WEIGHT: [1, 1, 1, 1, 1] # must be the same as the number of classes
  VSSM:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 15, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v3noz"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
DATA:
  TARGET_CLASS: [1, 2]
  AUG_TIMES: 4
# 89.0 + 15.2 + 118min/e + 48G

